import { sanitize } from './md.mjs';

const NO_SUMMARY = '_(no summary)_';
const NONE_YET = '_(none yet)_';

export function extractSummary(body) {
  if (!body) return NO_SUMMARY;
  const lines = body.split('\n');
  let i = 0;
  // Skip leading blank lines AND any heading-only / blank lines.
  while (i < lines.length) {
    const t = lines[i].trim();
    if (t === '' || /^#+\s/.test(t) || /^#+$/.test(t)) { i++; continue; }
    break;
  }
  if (i >= lines.length) return NO_SUMMARY;
  // Collect the paragraph (until next blank line).
  const para = [];
  while (i < lines.length && lines[i].trim() !== '') {
    para.push(lines[i].trim());
    i++;
  }
  if (para.length === 0) return NO_SUMMARY;
  const paragraph = para.join(' ').trim();
  if (paragraph === '') return NO_SUMMARY;
  // First sentence: end at . ! ? followed by whitespace or end-of-paragraph.
  const m = paragraph.match(/^(.+?[.!?])(\s|$)/);
  let summary;
  if (m) {
    summary = m[1];
  } else if (paragraph.length > 200) {
    summary = paragraph.slice(0, 200) + '…';
  } else {
    summary = paragraph;
  }
  return sanitize(summary);
}

export function renderIndex(groups) {
  const sections = [
    ['Concepts', 'concept'],
    ['People', 'person'],
    ['Sources', 'source'],
    ['Queries', 'query'],
  ];
  const out = [];
  out.push('# Wiki index');
  out.push('');
  out.push("_Regenerated by `pwiki index`. Don't edit by hand._");
  out.push('');
  for (const [heading, key] of sections) {
    out.push(`## ${heading}`);
    out.push('');
    const items = groups[key] ?? [];
    if (items.length === 0) {
      out.push(NONE_YET);
    } else {
      for (const it of items) {
        out.push(`- [${it.title}](${it.path}) — ${it.summary}`);
      }
    }
    out.push('');
  }
  return out.join('\n');
}
