import { describe, expect, it, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createFsDestination } from '../lib/destinations/fs.mjs';

let dir: string;

function writePage(rel: string, frontmatter: Record<string, unknown>, body: string) {
  const abs = join(dir, rel);
  mkdirSync(join(abs, '..'), { recursive: true });
  const fm = Object.entries(frontmatter).map(([k, v]) => {
    if (Array.isArray(v)) return `${k}: [${v.map(x => JSON.stringify(x)).join(', ')}]`;
    if (typeof v === 'string') return `${k}: ${v}`;
    return `${k}: ${JSON.stringify(v)}`;
  }).join('\n');
  writeFileSync(abs, `---\n${fm}\n---\n${body}`);
}

beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), 'pwiki-fs-index-'));
  mkdirSync(join(dir, 'docs', 'wiki', 'pages', 'concept'), { recursive: true });
  mkdirSync(join(dir, 'docs', 'wiki', 'pages', 'person'), { recursive: true });
  mkdirSync(join(dir, 'docs', 'wiki', 'pages', 'source'), { recursive: true });
  mkdirSync(join(dir, 'docs', 'wiki', 'pages', 'queries'), { recursive: true });
  writeFileSync(join(dir, 'docs', 'wiki', 'CLAUDE.md'), '# rules');
});
afterEach(() => rmSync(dir, { recursive: true, force: true }));

describe('fs.regenerateIndex', () => {
  it('writes index.md grouped by type, sorted by id', () => {
    writePage('docs/wiki/pages/concept/b.md', {
      id: 'b', type: 'concept', title: 'Beta',
      created: '2026-05-15', updated: '2026-05-15',
      status: 'active', tags: [], sources: [],
    }, '\n# Beta\n\nBeta description.\n');
    writePage('docs/wiki/pages/concept/a.md', {
      id: 'a', type: 'concept', title: 'Alpha',
      created: '2026-05-15', updated: '2026-05-15',
      status: 'active', tags: [], sources: [],
    }, '\n# Alpha\n\nAlpha description.\n');
    writePage('docs/wiki/pages/person/p.md', {
      id: 'p', type: 'person', title: 'Pat',
      created: '2026-05-15', updated: '2026-05-15',
      status: 'active', tags: [], sources: [],
    }, '\n# Pat\n\nA person.\n');

    const dest = createFsDestination({ rootPath: dir });
    const r = dest.regenerateIndex();
    expect(r.path).toBe('docs/wiki/index.md');
    expect(r.groups).toEqual({ concept: 2, person: 1, source: 0, query: 0 });
    expect(r.written).toBe(true);

    const text = readFileSync(join(dir, 'docs/wiki/index.md'), 'utf-8');
    expect(text).toContain('## Concepts\n\n- [Alpha](pages/concept/a.md) — Alpha description.\n- [Beta](pages/concept/b.md) — Beta description.');
    expect(text).toContain('## People\n\n- [Pat](pages/person/p.md) — A person.');
    expect(text).toContain('## Sources\n\n_(none yet)_');
    expect(text).toContain('## Queries\n\n_(none yet)_');
    expect(text).toContain("_Regenerated by `pwiki index`. Don't edit by hand._");
  });

  it('renders fully empty wiki with all _(none yet)_ groups', () => {
    const dest = createFsDestination({ rootPath: dir });
    const r = dest.regenerateIndex();
    expect(r.groups).toEqual({ concept: 0, person: 0, source: 0, query: 0 });
    const text = readFileSync(join(dir, 'docs/wiki/index.md'), 'utf-8');
    expect(text.match(/_\(none yet\)_/g)).toHaveLength(4);
  });

  it('uses _(no summary)_ for pages with empty body after H1', () => {
    writePage('docs/wiki/pages/concept/x.md', {
      id: 'x', type: 'concept', title: 'X',
      created: '2026-05-15', updated: '2026-05-15',
      status: 'active', tags: [], sources: [],
    }, '\n# X\n');
    const dest = createFsDestination({ rootPath: dir });
    dest.regenerateIndex();
    const text = readFileSync(join(dir, 'docs/wiki/index.md'), 'utf-8');
    expect(text).toContain('- [X](pages/concept/x.md) — _(no summary)_');
  });

  it('sanitizes bare <word> tokens in summary', () => {
    writePage('docs/wiki/pages/concept/x.md', {
      id: 'x', type: 'concept', title: 'X',
      created: '2026-05-15', updated: '2026-05-15',
      status: 'active', tags: [], sources: [],
    }, '\n# X\n\nReplace <tenant> in config.\n');
    const dest = createFsDestination({ rootPath: dir });
    dest.regenerateIndex();
    const text = readFileSync(join(dir, 'docs/wiki/index.md'), 'utf-8');
    expect(text).toContain('Replace `<tenant>` in config.');
  });

  it('overwrites an existing index.md', () => {
    writeFileSync(join(dir, 'docs', 'wiki', 'index.md'), '# stale content from a previous run\n');
    writePage('docs/wiki/pages/concept/a.md', {
      id: 'a', type: 'concept', title: 'A',
      created: '2026-05-15', updated: '2026-05-15',
      status: 'active', tags: [], sources: [],
    }, '\n# A\n\nFresh.\n');
    const dest = createFsDestination({ rootPath: dir });
    dest.regenerateIndex();
    const text = readFileSync(join(dir, 'docs', 'wiki', 'index.md'), 'utf-8');
    expect(text).not.toContain('stale content');
    expect(text).toContain('- [A](pages/concept/a.md) — Fresh.');
  });

  it('uses path relative to docs/wiki/ in link targets', () => {
    writePage('docs/wiki/pages/source/article-x-summary.md', {
      id: 'article-x-summary', type: 'source', title: 'Article X',
      created: '2026-05-15', updated: '2026-05-15',
      status: 'active', tags: [], sources: [],
      'source-url': 'https://x', 'source-type': 'article',
    }, '\n# Article X\n\nA summary.\n');
    const dest = createFsDestination({ rootPath: dir });
    dest.regenerateIndex();
    const text = readFileSync(join(dir, 'docs', 'wiki', 'index.md'), 'utf-8');
    expect(text).toContain('](pages/source/article-x-summary.md)');
    // Should NOT include the docs/wiki/ prefix in the link target
    expect(text).not.toContain('](docs/wiki/pages/source/');
  });
});
