import { describe, expect, it } from 'vitest';
import { extractSummary, renderIndex } from '../lib/index.mjs';

describe('extractSummary', () => {
  it('extracts the first sentence after H1', () => {
    const body = '\n# Foo\n\nKafka is a distributed log. It has partitions.\n\n## Key facts\n';
    expect(extractSummary(body)).toBe('Kafka is a distributed log.');
  });

  it('joins a multi-line paragraph before taking the first sentence', () => {
    const body = '\n# Foo\n\nKafka is a distributed\nlog system. More.\n';
    expect(extractSummary(body)).toBe('Kafka is a distributed log system.');
  });

  it('handles ? and ! as sentence terminators', () => {
    const body = '\n# Foo\n\nIs this OK? Yes.\n';
    expect(extractSummary(body)).toBe('Is this OK?');
  });

  it('truncates to 200 chars + ellipsis when no terminator found', () => {
    const long = 'a'.repeat(250);
    const body = `\n# Foo\n\n${long}\n`;
    const r = extractSummary(body);
    expect(r.length).toBe(201); // 200 chars + …
    expect(r.endsWith('…')).toBe(true);
  });

  it('returns _(no summary)_ for empty body', () => {
    expect(extractSummary('')).toBe('_(no summary)_');
  });

  it('returns _(no summary)_ for body with only H1', () => {
    expect(extractSummary('\n# Foo\n')).toBe('_(no summary)_');
  });

  it('returns _(no summary)_ for body with only headings', () => {
    const body = '\n# Foo\n\n## Sub\n\n### SubSub\n';
    expect(extractSummary(body)).toBe('_(no summary)_');
  });

  it('skips H1 and any leading heading lines', () => {
    const body = '\n# Foo\n\n## Sub\n\nReal paragraph here.\n';
    expect(extractSummary(body)).toBe('Real paragraph here.');
  });

  it('sanitizes bare <word> tokens in the summary', () => {
    const body = '\n# Foo\n\nReplace <tenant> in the config to deploy.\n';
    expect(extractSummary(body)).toBe('Replace `<tenant>` in the config to deploy.');
  });

  it('handles Cyrillic content', () => {
    const body = '\n# Кафка\n\nКафка — это распределённый лог.\n';
    expect(extractSummary(body)).toBe('Кафка — это распределённый лог.');
  });
});

describe('renderIndex', () => {
  it('renders all four sections in order', () => {
    const groups = {
      concept: [
        { title: 'Foo', path: 'pages/concept/foo.md', summary: 'A foo.' },
      ],
      person: [],
      source: [
        { title: 'Article X', path: 'pages/source/article-x-summary.md', summary: 'Summary.' },
      ],
      query: [],
    };
    const out = renderIndex(groups);
    expect(out).toBe(
      '# Wiki index\n' +
      '\n' +
      "_Regenerated by `pwiki index`. Don't edit by hand._\n" +
      '\n' +
      '## Concepts\n' +
      '\n' +
      '- [Foo](pages/concept/foo.md) — A foo.\n' +
      '\n' +
      '## People\n' +
      '\n' +
      '_(none yet)_\n' +
      '\n' +
      '## Sources\n' +
      '\n' +
      '- [Article X](pages/source/article-x-summary.md) — Summary.\n' +
      '\n' +
      '## Queries\n' +
      '\n' +
      '_(none yet)_\n'
    );
  });

  it('renders an entirely empty wiki', () => {
    const out = renderIndex({ concept: [], person: [], source: [], query: [] });
    expect(out).toContain('## Concepts\n\n_(none yet)_');
    expect(out).toContain('## People\n\n_(none yet)_');
    expect(out).toContain('## Sources\n\n_(none yet)_');
    expect(out).toContain('## Queries\n\n_(none yet)_');
  });

  it('lists multiple items in the order received', () => {
    const groups = {
      concept: [
        { title: 'A', path: 'pages/concept/a.md', summary: 'Sa.' },
        { title: 'B', path: 'pages/concept/b.md', summary: 'Sb.' },
      ],
      person: [], source: [], query: [],
    };
    const out = renderIndex(groups);
    const conceptSection = out.split('## People')[0];
    expect(conceptSection).toContain('- [A](pages/concept/a.md) — Sa.\n- [B](pages/concept/b.md) — Sb.\n');
  });
});
